### ISSUE TITLE
Release version 3.4.4 not available as downloadable release

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-Sparql#5]
According to commit https://github.com/Daniel-KM/Omeka-S-module-Sparql/commit/90da1930322b22fe7c481a15207859e77aa55cba version 3.4.4 of the module is available, but it's not downloadable via https://github.com/Daniel-KM/Omeka-S-module-Sparql/releases ?

**Comment by Daniel-KM** [comment]
Yes, it is mainly to support omeka s v4.1. Releases will be published in a few days.
